# Configurações Gerais
ipc = true
splash = false

# Configuração para o monitor do notebook
wallpaper {
    monitor = eDP-1
    path = endereco do walpaper
    fit_mode = cover
}

# Configuração para o monitor externo (se estiver conectado)
wallpaper {
    monitor = HDMI-A-1
    path = endereco do walpaper
    fit_mode = cover
}

# Fallback (caso algum monitor novo seja conectado)
wallpaper {
    monitor = 
    path =  endereco do walpaper
    fit_mode = cover
}
