# Configurações Gerais
ipc = true
splash = false

# Configuração para o monitor do notebook
wallpaper {
    monitor = eDP-1
    path = ~/.config/hypr/walpaper/zelda.jpg
    fit_mode = cover
}

# Configuração para o monitor externo (se estiver conectado)
wallpaper {
    monitor = HDMI-A-1
    path = ~/.config/hypr/walpaper/zelda.jpg
    fit_mode = cover
}

# Fallback (caso algum monitor novo seja conectado)
wallpaper {
    monitor = 
    path =  ~/.config/hypr/walpaper/3.jpeg
    fit_mode = cover
}
